### PR TITLE
Multiple tags files (and other improvements)

### PR DESCRIPTION
**Pull request by friedbrice**
Co-requisite with https://github.com/MercuryTechnologies/mercury-web-backend/pull/26568

* [DUX-2035](https://linear.app/mercury/issue/DUX-2035/symlink-required-cli-tools): Configure `grep` path.
* [DUX-2037](https://linear.app/mercury/issue/DUX-2037/support-merging-of-workspace-settings-and-vscodealloglotjson): Support merging of workspace and fallback config.
* [DUX-2041](https://linear.app/mercury/issue/DUX-2041/support-multiple-tags-configs): Support multiple tags files.

### CODE REVIEW

**Comment by michaelkitson** [comment]
Just as an option to consider if you haven't, it seems like it might be possible to just not use PCRE syntax in the regex? I think `\t` is the only PCRE thing you're using, and could be replaced with a literal tab.

Just a thought, not well researched.

**Comment by friedbrice** [comment]
Thanks, @michaelkitson! I'll try that.

**Review by azuzunaga — COMMENTED** [review]
Looks awesome. Let me know when it's ready for review and I'll stamp.

**Comment by friedbrice** [comment]
@michaelkitson I'm going to go with requiring GNU Grep, because I spent too much time pulling my hair out trying to figure out a CLI invocation that worked for _both_ GNU Grep _and_ BSD Grep -_-

**Review by azuzunaga — APPROVED** [review]

**Pull request merged**
